chore: better formatting on commit-msg hook

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,10 +1,24 @@
-#!/usr/bin/env sh
+#!/bin/bash
+
+##
+# Git hook that enforces conventional commits
+# https://www.conventionalcommits.org
+##
+
+RESET='\033[0m'
+GREEN='\033[0;32m'
+RED='\033[0;31m'
+
 
 if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(!?)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Message must follow the pattern '<type>: <description>' (https://www.conventionalcommits.org/en/v1.0.0/)" >&2
+    echo -e "${RED}\nAborting commit. Your commit message is invalid.\n" >&2
+    echo "An example of a valid message is: " >&2
+    echo "  feat(login): add the 'remember me' checkbox" >&2
+    echo "More details at: https://www.conventionalcommits.org/en/v1.0.0/#summary">&2
     exit 1
 fi
-if ! head -1 "$1" | grep -qE "^.{1,72}$"; then
-    echo "Aborting commit. Your commit message is too long" >&2
+if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
+    echo -e "${RED}\nAborting commit. Your commit message is too long." >&2
+    echo "Maximum length is 50 characters" >&2
     exit 1
 fi
